// @generated
// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Events {
    #[prost(message, repeated, tag="1")]
    pub deposits: ::prost::alloc::vec::Vec<Deposit>,
    #[prost(message, repeated, tag="2")]
    pub withdraws: ::prost::alloc::vec::Vec<Withdraw>,
    #[prost(message, repeated, tag="3")]
    pub transfers: ::prost::alloc::vec::Vec<Transfer>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StateChanges {
    #[prost(message, repeated, tag="1")]
    pub changes: ::prost::alloc::vec::Vec<StateChange>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StateChange {
    #[prost(string, tag="1")]
    pub vault_address: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub metric: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub previous_value: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub current_value: ::prost::alloc::string::String,
    #[prost(uint64, tag="5")]
    pub block_number: u64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Deposit {
    #[prost(string, tag="1")]
    pub vault_address: ::prost::alloc::string::String,
    #[prost(bytes="vec", tag="2")]
    pub sender: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="3")]
    pub owner: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag="4")]
    pub assets: ::prost::alloc::string::String,
    #[prost(string, tag="5")]
    pub shares: ::prost::alloc::string::String,
    #[prost(string, tag="6")]
    pub evt_tx_hash: ::prost::alloc::string::String,
    #[prost(uint32, tag="7")]
    pub evt_index: u32,
    #[prost(message, optional, tag="8")]
    pub evt_block_time: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(uint64, tag="9")]
    pub evt_block_number: u64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Withdraw {
    #[prost(string, tag="1")]
    pub vault_address: ::prost::alloc::string::String,
    #[prost(bytes="vec", tag="2")]
    pub sender: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="3")]
    pub receiver: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="4")]
    pub owner: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag="5")]
    pub assets: ::prost::alloc::string::String,
    #[prost(string, tag="6")]
    pub shares: ::prost::alloc::string::String,
    #[prost(string, tag="7")]
    pub evt_tx_hash: ::prost::alloc::string::String,
    #[prost(uint32, tag="8")]
    pub evt_index: u32,
    #[prost(message, optional, tag="9")]
    pub evt_block_time: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(uint64, tag="10")]
    pub evt_block_number: u64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Transfer {
    #[prost(string, tag="1")]
    pub vault_address: ::prost::alloc::string::String,
    #[prost(bytes="vec", tag="2")]
    pub from: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="3")]
    pub to: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag="4")]
    pub value: ::prost::alloc::string::String,
    #[prost(string, tag="5")]
    pub evt_tx_hash: ::prost::alloc::string::String,
    #[prost(uint32, tag="6")]
    pub evt_index: u32,
    #[prost(message, optional, tag="7")]
    pub evt_block_time: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(uint64, tag="8")]
    pub evt_block_number: u64,
    #[prost(string, tag="9")]
    pub asset_address: ::prost::alloc::string::String,
    #[prost(bool, tag="10")]
    pub is_asset_transfer: bool,
}
// @@protoc_insertion_point(module)
